apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  labels:
    app: guestbook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook-ui
        image: wonilinfra/guestbook:41ece3cc602d074855b3a21708b1118a4db8dccf
        ports:
        - containerPort: 80
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: REDIS_MASTER_SERVICE_HOST
          value: redis-master

# trigger Wed Aug 27 04:16:38 UTC 2025
# autosync test Wed Aug 27 05:35:09 UTC 2025
# autosync test Wed Aug 27 05:36:15 UTC 2025
